### ISSUE TITLE
Unable to open pid file /var/run/hhvm/pid for write

### ISSUE THREAD

**Issue by etcook** [estebanmatias92/docker-hhvm#1]
2015-02-18T23:35:08.804589893Z Unable to open pid file /var/run/hhvm/pid for write

I believe you need to create the hhvm directory so the pid file can be written.

I'm using 3.5-fastcgi

**Comment by estebanmatias92** [comment]
Thanks @etcook,

You are right, in two hours from now should be fixed (due to Docker automated-build). 24bcf952476e0691c155a34ce987019b2230fdd9

**Comment by etcook** [comment]
:thumbsup: Thanks @estebanmatias92
