### ISSUE TITLE
Having issue with running hhvm as a user

### ISSUE THREAD

**Issue by etcook** [estebanmatias92/docker-hhvm#6]
I'm trying to pass it the --user flag, but when I do that, it doesn't seem like it has that capability.

I'm getting the follow error:
cap_set_proc failed

Unfortunately, it isn't giving any more information than that.

**Comment by estebanmatias92** [comment]
Thanks for the ticket @etcook.

Sorry for the late anwser.

Is from systemd that --user flag? 
I would like to start test to fix this, i need replicate the problem. Do you remember the steps to get that error? that would be really usefull.

I am going to start the test runing the hhvm deamon with systemd and its --user flag.
I will do everything that i can. I will be aware for the answer.

Thanks.

**Comment by etcook** [comment]
@estebanmatias92 Thanks for getting back to me. I believe I fixed this by making sure the image runs as privileged.
