### ISSUE TITLE
HHVM 3.8.x support

### ISSUE THREAD

**Issue by zakhenry** [estebanmatias92/docker-hhvm#9]
@estebanmatias92 do you have plans of adding a container for HHVM 3.8.x? It brings with it fixes for xdebug which is a pain currently as I'm having to use a phpfpm container for debugging.

**Comment by estebanmatias92** [comment]
Upgraded, should be working right now.

**Comment by zakhenry** [comment]
@estebanmatias92 awesome, I'll test it out now.
